---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, elasticsearch-install]

- include: configure.yml
  tags: [elasticsearch, elasticsearch-configure]

- include: aws.yml
  tags: [elasticsearch, elasticsearch-plugins, aws]

- include: plugins.yml
  tags: [elasticsearch, elasticsearch-plugins]

- service: name=elasticsearch state=started enabled=yes
  tags: [elasticsearch]
