# Install Http Basic Auth plugin (see https://github.com/Asquera/elasticsearch-http-basic)
#
# The following variables need to be defined in your playbook or inventory:
#
# http_basic_version: 1.3.2
# http_basic_enabled: true (defaults to true)
# http_basic_log: true (defaults to true)
# http_basic_user: user (defaults to admin)
# http_basic_password: password (defaults to admin_pw)
- name: ensure http basic folder exists
  file: path={{ elasticsearch_plugindir }}/http-basic owner=elasticsearch group=elasticsearch state=directory

- name: download http-basic plugin
  get_url: url=https://github.com/Asquera/elasticsearch-http-basic/releases/download/{{ http_basic_version }}/elasticsearch-http-basic-{{ http_basic_version }}.jar dest={{ elasticsearch_plugindir }}/http-basic/elasticsearch-http-basic-{{ http_basic_version }}.jar
